name = "SFRP"
author = "Groundix"
version = "test"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b191d84ff1ad9721f890690d8e5d7531987416bbd86681d7e7de78af338acb88"

[versions]
minecraft = "1.19.3"

[options]
meta-folder = "plugins"
